steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      echo "Mengakses secret..."
      gcloud secrets versions access latest --secret=gcp-credentials > credential.json || { echo "Error: Tidak dapat mengakses secret"; exit 1; }

- name: 'python:3.9'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      echo "Menginstall dependencies..."
      pip install -r requirements.txt || { echo "Error: Gagal install dependencies"; exit 1; }
      echo "Menjalankan aplikasi..."
      python app.py || { echo "Error: Aplikasi gagal dijalankan"; exit 1; }

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - run
    - deploy
    - my-app
    - --source=.
    - --platform=managed
    - --region=asia-southeast2
    - --allow-unauthenticated
    - --update-env-vars=GOOGLE_APPLICATION_CREDENTIALS=credential.json

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
